---

name: deeplabv3p
gops: 181.47

model: $(home)/deeplabv3p_resnet50_os8_cityscapes/

BM1684:
  fp_compile_options:
    python3 -m bmpaddle
      --model $(model)
      --shapes [1,3,640,320]
      --net_name $(name)
      --target $(target)
      --enable_profile True

  time_only_cali:
    python3 -m ufw.cali.cali_model
      --model=$(model)/model.pdmodel
      --input_shapes="[1,3,640,320]"
      --net_name=$(name)
      --cali_iterations=1
      --target=$(target)
      --input_name="x"
      --output_name="argmax_0.tmp_0"
      --test_iterations=1
      --debug_cmd="use_fake_data_to_test;not_suspend;not_call_bmnetu"

# int8_model: $(workdir)/$(name)_bmpaddle_deploy_int8_unique_top.prototxt
# int8_weight: $(workdir)/$(name)_bmpaddle.int8umodel

# bmnetu_batch_sizes: [1, 4]
# bmnetu_options:
#   --model $(int8_model)
#   --weight $(int8_weight)
#   --target $(target)
#   --enable_profile True

# precision: false

fp_batch_sizes: [1, 4]

BM1684X:
  fp_loops:
    - build_env:
        - BMCOMPILER_GROUP_SEARCH_COUNT=1
      fp_outdir_template: "{}b.fp32.compilation"
      prec: FP32
    - build_env:
        - BMCOMPILER_LAYER_DTYPE_MODE=fp16
        - BMCOMPILER_GROUP_SEARCH_COUNT=1
      fp_outdir_template: "{}b.fp16.compilation"
      prec: FP16

  fp_compile_options:
    python3 -m bmpaddle
    --model $(model)
    --shapes [1,3,640,320]
    --net_name $(name)
    --target $(target)
    --enable_profile True
    --cmp True
    --enable_profile True
    --output="bilinear_interp_v2_2.tmp_0"